// <auto-generated />
using System;
using EmptyParcelLocker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmptyParcelLocker.API.Migrations
{
    [DbContext(typeof(EmptyParcelLockerDbContext))]
    partial class EmptyParcelLockerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd39b1e1-e3f8-436e-9956-1d1ee8de3aa3"),
                            ApartmentNumber = "",
                            BuildingNumber = "61",
                            CityName = "Cieszyn",
                            Street = "Frysztacka",
                            ZipCode = "43-400"
                        });
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<Guid>("LockerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelLockerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Lockers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f68494a-434a-4d7a-b047-bceec0eff40a"),
                            IsEmpty = true,
                            LockerTypeId = new Guid("c5622830-eb07-455b-8c42-8dcbd6c8c926"),
                            ParcelLockerId = new Guid("22e88beb-98bb-4922-adba-538e86f5834b")
                        },
                        new
                        {
                            Id = new Guid("50e9dae7-8a83-4a29-b89b-6083804893bf"),
                            IsEmpty = false,
                            LockerTypeId = new Guid("c5622830-eb07-455b-8c42-8dcbd6c8c926"),
                            ParcelLockerId = new Guid("22e88beb-98bb-4922-adba-538e86f5834b")
                        },
                        new
                        {
                            Id = new Guid("3058f64e-ba63-460d-9013-70244f25b036"),
                            IsEmpty = true,
                            LockerTypeId = new Guid("c5622830-eb07-455b-8c42-8dcbd6c8c926"),
                            ParcelLockerId = new Guid("22e88beb-98bb-4922-adba-538e86f5834b")
                        });
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.LockerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LockerTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5622830-eb07-455b-8c42-8dcbd6c8c926"),
                            MaxHeight = 80,
                            MaxLength = 640,
                            MaxWeight = 25,
                            MaxWidth = 380,
                            Name = "small"
                        },
                        new
                        {
                            Id = new Guid("09b9faae-6598-4e47-bce6-37cdfb46b7bf"),
                            MaxHeight = 190,
                            MaxLength = 640,
                            MaxWeight = 25,
                            MaxWidth = 380,
                            Name = "medium"
                        },
                        new
                        {
                            Id = new Guid("f4dd7a2e-90e9-4cab-b7dc-38a6ad528403"),
                            MaxHeight = 410,
                            MaxLength = 640,
                            MaxWeight = 25,
                            MaxWidth = 380,
                            Name = "large"
                        });
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParcelLockers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22e88beb-98bb-4922-adba-538e86f5834b"),
                            AddressId = new Guid("dd39b1e1-e3f8-436e-9956-1d1ee8de3aa3"),
                            Latitude = 49.757507942840931,
                            Longitude = 18.622906166106151,
                            Name = "CSZ08M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
