// <auto-generated />
using System;
using EmptyParcelLocker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmptyParcelLocker.API.Migrations
{
    [DbContext(typeof(EmptyParcelLockerDbContext))]
    [Migration("20220905084301_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<Guid>("LockerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelLocerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParcelLockerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LockerTypeId");

                    b.HasIndex("ParcelLockerId");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.LockerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LockerTypes");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParcelLockers");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Locker", b =>
                {
                    b.HasOne("EmptyParcelLocker.API.Data.Models.LockerType", "LockerType")
                        .WithMany()
                        .HasForeignKey("LockerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmptyParcelLocker.API.Data.Models.ParcelLocker", null)
                        .WithMany("Lockers")
                        .HasForeignKey("ParcelLockerId");

                    b.Navigation("LockerType");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLocker", b =>
                {
                    b.Navigation("Lockers");
                });
#pragma warning restore 612, 618
        }
    }
}
