// <auto-generated />
using System;
using EmptyParcelLocker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmptyParcelLocker.API.Migrations
{
    [DbContext(typeof(ParcelLockerDbContext))]
    [Migration("20220822102532_Intial Migration")]
    partial class IntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Locker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<Guid>("LockerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelLockerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LockerTypeId");

                    b.HasIndex("ParcelLockerId");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.LockerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LockerTypes");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParcelLockers");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLockerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParcelLockerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelLockerId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.Locker", b =>
                {
                    b.HasOne("EmptyParcelLocker.API.Data.Models.LockerType", "LockerType")
                        .WithMany()
                        .HasForeignKey("LockerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmptyParcelLocker.API.Data.Models.ParcelLocker", "ParcelLocker")
                        .WithMany("Lockers")
                        .HasForeignKey("ParcelLockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LockerType");

                    b.Navigation("ParcelLocker");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLockerAddress", b =>
                {
                    b.HasOne("EmptyParcelLocker.API.Data.Models.ParcelLocker", "ParcelLocker")
                        .WithOne("ParcelLockerAddress")
                        .HasForeignKey("EmptyParcelLocker.API.Data.Models.ParcelLockerAddress", "ParcelLockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelLocker");
                });

            modelBuilder.Entity("EmptyParcelLocker.API.Data.Models.ParcelLocker", b =>
                {
                    b.Navigation("Lockers");

                    b.Navigation("ParcelLockerAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
